defaults:
#baseurl: systems.shyran.pp.ua
#host: systems.shyran.pp.ua
#url: https://systems.shyran.pp.ua
#index: source/index.html
encoding: utf-8
disable_disk_cache: BOOL
profile: BOOL
livereload: BOOL
path: ""
# destination: "jekyll.branch.output"
plugins_dir: _plugins
gem: jekyll-minibundle
timezone: Europe/Kiev
exclude: 
.readme
#README.md
# <!-- * -->
title: Shyran Systems
author: @shyransystems
layout: page
theme: minimal



